---
daysUntilStale: 28
daysUntilClose: 14
exemptLabels:
  - bounty
  - critical
  - feature
  - technical debt
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be _closed in two weeks_ if no further activity occurs.
  :heart: Thank you for your contributions to [OWASP Juice Shop](https://owasp-juice.shop)!
closeComment: false
